---
image_resource:
  type: registry-image
  source: { repository: c2cnetworking/deploy-light }

platform: linux

inputs:
  - name: tarballs
  - name: cf-networking-release-ci
  - name: deployments-repo

run:
  path: cf-networking-release-ci/ci/tasks/upload-release-tarball/task

params:
  ENVIRONMENT_NAME: ~
