---
platform: linux

image_resource:
  type: registry-image
  source: { repository: c2cnetworking/deploy-light }

inputs:
  - name: cf-networking-release-ci
  - name: test-config
  - name: variables
    optional: true

params:
  ENVIRONMENT_NAME: ~
  CONFIG_POSTFIX: ~
  SMOKE_PASSWORD: ~
  TEST_CONFIG_DIR: ~

outputs:
  - name: smoke-config

run:
  path: cf-networking-release-ci/ci/tasks/setup-smoke-config/task
