---
image_resource:
  type: registry-image
  source: { repository: c2cnetworking/deploy }

platform: linux

inputs:
  - name: version
  - name: cf-networking-release-ci
  - name: networking-oss-deployments
  - name: silk-tarball
  - name: silk

outputs:
  - name: final-release
  - name: release

params:
  GCP_BLOBSTORE_SERVICE_ACCOUNT_KEY:

run:
  path: cf-networking-release-ci/ci/tasks/silk-shipit/task
