---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: c2cnetworking/deploy-light

inputs:
  - name: cf-networking-release-ci
  - name: deployments-repo

params:
  BACKUP_ID: ~
  DATABASE_NAME: ~
  ENVIRONMENT_NAME: ~
  PROJECT_ID: ~

run:
  path: cf-networking-release-ci/ci/tasks/reinitialize-database/task
