---
platform: linux

image_resource:
  type: registry-image
  source: { repository: c2cnetworking/dev-postgres }

inputs:
  - name: cf-networking-release-ci
  - name: variables

params: []

run:
  path: cf-networking-release-ci/ci/tasks/verify-api-ready-toolsmiths/task
