---
platform: linux

image_resource:
  type: registry-image
  source: { repository: c2cnetworking/dev-postgres }

inputs:
  - name: cf-networking-release-ci
  - name: test-config
  - name: cf-networking

outputs:
  - name: network-stats

params:
    CONFIG: ~
    TEST_NAME: acceptance

run:
  path: cf-networking-release-ci/ci/tasks/acceptance-tests-toolsmiths/task
