---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/dev-postgres }

inputs:
  - name: cf-networking-release-ci
  - name: test-config
  - name: cf-networking
  - name: variables

outputs:
  - name: network-stats

params:
    CONFIG: test-config/test-config.json
    TEST_NAME: acceptance

run:
  path: cf-networking-release-ci/ci/tasks/acceptance-tests/task
