---
image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks
    tag: latest

platform: linux

inputs:
  - name: cf-deployment-concourse-tasks
  - name: cf-networking-release-ci
  - name: bbl-state
    optional: true
  - name: toolsmiths-env
    optional: true
  - name: local-release

run:
  path: cf-networking-release-ci/ci/tasks/upload-local-release/task

params:
  BBL_STATE_DIR: bbl-state
