---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: c2cnetworking/deploy-light

inputs:
  - name: cf-networking
  - name: cf-networking-release-ci
  - name: test-config
  - name: toolsmiths-env

params:
  CONFIG: ~

run:
  path: cf-networking-release-ci/ci/tasks/test-nats-performance/task
