---
platform: linux

image_resource:
  type: registry-image
  source: { repository: c2cnetworking/deploy-light }

inputs:
  - name: cf-networking-release-ci
  - name: cf-networking

run:
  path: cf-networking-release-ci/ci/tasks/check-empty-networking-opsfile/task
