---
image_resource:
  type: registry-image
  source: { repository: c2cnetworking/deploy }

platform: linux

inputs:
  - name: version
  - name: cf-networking-release-ci
  - name: master-repo
  - name: dev-repo

run:
  path: cf-networking-release-ci/ci/tasks/checkit/task
