---
image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/deploy
    tag: latest

platform: linux

inputs:
  - name: cf-deployment-concourse-tasks
  - name: cf-networking-dev
  - name: cf-networking-release-ci
  - name: bbl-state
    optional: true
  - name: toolsmiths-env
    optional: true

run:
  path: cf-networking-release-ci/ci/tasks/upload-acceptance-test-release/task

params:
  BBL_STATE_DIR:
