---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: bbl-state
- name: cf-networking-release-ci
- name: bosh-bootloader

outputs:
- name: updated-bbl-state

params:
  ENVIRONMENT: ~
  GIT_COMMIT_EMAIL:
  GIT_COMMIT_USERNAME:

run:
  path: cf-networking-release-ci/ci/tasks/add-parent-dns/task
