---
platform: linux

image_resource:
  type: registry-image
  source: { repository: c2cnetworking/dev-postgres }

inputs:
  - name: cf-networking
  - name: cf-networking-release-ci
  - name: smoke-config

params:
    ENVIRONMENT_TAG: ~
    DATADOG_API_KEY: ~

run:
  path: cf-networking-release-ci/ci/tasks/smoke-tests-sd/task
